### ISSUE TITLE
格式錯誤之後

### ISSUE THREAD

**Issue by tim85145** [GarrettTW/LineBot_ReportMessage#1]
請問我們在使用你的機器人時，不小心出現錯誤的格式，原本三位數的學號多了一位數變成四位數，之後進行[回報統計]以及[輸出回報]後便一直出現錯誤，如下：

錯誤原因: '<' not supported between instances of 'str' and 'int'

**Comment by GarrettTW** [comment]
感謝你的回報!
**錯誤原因:**
以前我們軍中使用學號為5碼，有意義數字是最後3碼(有些人懶惰只會輸入3碼)
故我開發的時候就會限制學號的長度，造成存資料時候長度判斷錯誤

**已修正:**
學號輸入甚麼，就原封不動地存進去!
